FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# FntBeacons API

API for iBeacon Devices management.

## iBeacon Devices List [/dl{id}]

### List All Devices [GET]

+ Response 200 (application/json)

        [
            {
                "name": "iBeacon Exit room 1",
                "type": "Estimote",
                "id": 1,
                "major": 3556
                "minor": 15
                "address": 32569,
            }
        ]

## iBeacon Devices Definition [/dc]

### Create a New Device [POST]

Add a new device.

+ Request (application/json)

            {
                "name": "New iBeacon",
                "type": "Estimote",
                "major": 3556
                "minor": 15
            }

+ Response 201 (application/json)

    + Headers

            Location: /dl/1
            
    + Body
    
            {
                "id":1
            }


## iBeacon Devices Location [/ds]

### Create a New Device [POST]

Set a new device location.

+ Request (application/json)

        {
            "id":1,
            "name": "iBeacon Enter room 1",
            "address" : 32569
        }

+ Response 204