FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# FntGallery API

First API version for an exhibit description

## Gallery [/g]

### List All Galleries [GET]

+ Response 200 (application/json)

        [
            {
                "gid": 1,
                "lang": "CZ",
                "name": "Galerie Václava Špály",
                "poster": "galerie.png",
                "published_at": "2015-08-05T08:40:51",
                "about": "Short introduction",
                "address":  {
                                "city": "Prague",
                                "street": "Narodni 10",
                                "zip": "110 00",
                                "gps": "",
                                "wtg": "jak se k nam dostanete-popis"
                            },
                "contact": [ {
                               "name":  "Pavel Lagner",
                               "title": "kurátor",
                               "phone": "420 000 0000"
                               "email": "pl@email.cz"
                             }
                            ],
                "ohours": [ 
                            {
                               "item": "Daily 08:00-18:00"
                            }
                          ],
                "url": "http://www.galerievaclavaspaly.cz",
                "price": [ { "item": "Základní vstupné",
                             "value": "100"
                             "crncy": "CZK"
                           }
                         ],
            }
        ]

## Exhibition [/h]

### List All Exhibitions [GET]

+ Response 200 (application/json)

        [
            {
                "gid": 1,
                "lang": "CZ",
                "published_at": "2015-08-05T08:40:51",
                "current": 10,
                "exhibition": [ {
                                    "hid:": 10
                                    "name": "Jan Pistek",
                                    "from": "01-05-2017",
                                    "to":   "01-08-2017",
                                    "about": "short introduction"
                                    "author": "short introduction"
                                }
                              ],
                "poster": "pistek.png",
        ]


## Exhibit [/e]

### List All Exhibits [GET]

+ Response 200 (application/json)

        [
            {
                "gid": 1,
                "lang": "CZ",
                "published_at": "2015-08-05T08:40:51",
                "created": "1958",
                "technique": "olejomalba",
                "size": "60x80",
                "original": "yes",
                "gallery": "zapujcen ze soukrome sbirky",
                "picture": "obraz1.png",
                "video:": "obraz1.mpeg",
                "title": "Title",
                "about": "Exhibit description",
                "author": "an optional author statement",
                "url": "an optional url for further reading"
            }    
        ]